security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # activate different ways to authenticate
            # form_login, remember_me, logout can be activated here if needed

    access_control:
        # Restrict access to the admin routes to ROLE_ADMIN only
        - { path: ^/admin, roles: ROLE_ADMIN }
        
        # Restrict the creation of a new article to authenticated users (ROLE_USER)
        - { path: ^/article/new, roles: ROLE_USER }
        
        # Restrict article editing to the article's creator (ROLE_USER)
        - { path: ^/article/\d+/edit, roles: ROLE_USER }

        # Optionally restrict access to the profile page for logged-in users
        - { path: ^/profile, roles: ROLE_USER }
